language: cpp
compiler: g++
notifications:
  email: false
sudo: required
addons:
  apt:
    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'kalakris-cmake']
    packages: ['clang-3.7', 'cmake']
install:
- sudo apt-get -y upgrade
- sudo apt-get install cmake
- chmod +x googleTester.sh
script: "bash -c ./googleTester.sh"
