language: cpp
compiler: g++
notifications:
  email: false
sudo: required
install:
- sudo apt-get install software-properties-common
- sudo add-apt-repository ppa:george-edison55/cmake-3.x
- sudo apt-get update
- sudo apt-get upgrade
- sudo apt-get install cmake
- chmod +x googleTester.sh
script: "bash -c ./googleTester.sh"
