language: cpp
compiler: g++
notifications:
  email: false
sudo: required
addons:
  apt:
    sources:
      - ppa:george-edison55/cmake-3.x
    packages:
      - cmake
install:
- sudo apt-get update
- sudo apt-get install cmake
- chmod +x googleTester.sh installCmake.sh
script: "bash -c ./googleTester.sh"
